name = "ReadDBC"
uuid = "79d50320-df92-4ae6-9b90-d461b5bc1756"
authors = ["Bright-yaw <amenubright@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
